### ISSUE TITLE
Demonstrate multi-tenancy

### ISSUE THREAD

**Issue by docktermj** [Senzing/kubernetes-demo#99]
Using aspects of Kubernetes like "namespaces", "PVCs",  services, demonstrate how multi-tenancy can be achieved.

**Comment by brianmacy** [comment]
* Data should be isolated
* Every tenant should have it's own data encryption key
* Per tenant SSL client certs should be used to auth against the REST API

**Comment by docktermj** [comment]
### References

1. https://stackoverflow.com/questions/37221483/service-located-in-another-namespace

**Comment by docktermj** [comment]
Using the "Namespaces as a Service" approach.
https://kubernetes.io/blog/2021/04/15/three-tenancy-models-for-kubernetes/#namespaces-as-a-service

**Comment by roncewind** [comment]
I think we can remove this issue now.

**Comment by docktermj** [comment]
The work done on this is at https://github.com/Senzing/kubernetes-demo/blob/main/docs/helm-rabbitmq-postgresql-multi-tenant/README.md
